### ISSUE TITLE
Call out exception while dowloading the file

### ISSUE THREAD

**Issue by prietyc123** [include97logic/Auto_GoogleDrive_Downloads#1]
@include97logic I have a dummy file with publicly accessible permission. So I ran 

> python3 auto_download.py --file_link <file-link>

and got error

```
INFO:root:Downloading, Please check Downloads Folder
INFO:root:Testing Method: get_file_id
INFO:root:Testing Method:read_checkout_xl
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "auto_download.py", line 65, in <module>
    url_val = obj.read_checkout_xl("<file-link>")
  File "auto_download.py", line 37, in read_checkout_xl
    df = pd.read_csv(readable_url)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/common.py", line 670, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/common.py", line 339, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/common.py", line 239, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
```
https://github.com/include97logic/Auto_GoogleDrive_Downloads/blob/52c3625fdec69bb58b9b6e052a61e27364f383fa/auto_download.py#L59

I feel here you need to handle some exceptions accordingly. Correct me if I am wrong. Like I can see 404 even. Please feel free to share your thoughts on this.

**Comment by prietyc123** [comment]
Another interesting point I am thinking loud is, what if the file is not accessible publicly. Should we look for login code using api. Looking forward for a better suggestion from you.

**Comment by include97logic** [comment]
@prietyc123 Thanks a lot for the suggestions! & finding this issue
1. The first issue is because of the --test parameter, while checking the parameter I had mentioned 'False' By default, &  condition for test execution was' if its not None'. so condition was always evaluated to true & Tests were initiated.
That can be fixed by : Changing line No. 60 .**from**  if args.test is not None: to  **if args.test == 'True':**

Since that test argument was not None always it was executing the defined test case. So basically error was, while performing the test execution on script the second test case **read_checkout_xl** method call,
which downloads files from spreadsheet consisting of file links & file name. has encountered  this error because of 
missing python certificates, that can be resolved by installing the certificates.


2. We can add one more feature to this code i.e. downloading all the files from given **folder URL**, for that we can add one more parameter '--folder link' which in turn drives the function built on top of 'google drive downloader' module. where extraction of each file URLs from given Drive folder becomes easy & existing download function can be called for extracted file URL's & download. & **also it enables file download which are not publicly accessible**.  but to use this feature user should have clientsecret.json from google API console for drive access.

**Comment by prietyc123** [comment]
> & also it enables file download which are not publicly accessible. but to use this feature user should have clientsecret.json from google API console for drive access.

Could you please try to implement that feature.

**Comment by include97logic** [comment]
@prietyc123 The above mentioned two features have been implemented, tested & uploaded.
1. Private File Download:
Parameters: python auto_download.py --private_file_link  **FileLink**  **FileName**
Eg.  python auto_download.py --private_file_link https://drive.google.com/file/d/13z2o1X_OPiz9JSif0noI0klgYWtdpRWN/view?usp=sharing cat.png
The Above mentioned image is present in a private folder, & also the file is in private / Restricted Mode.
![image](https://user-images.githubusercontent.com/38622189/154615699-f2592837-0922-46aa-9047-401c37bf16e4.png)

![Untitled](https://user-images.githubusercontent.com/38622189/154616947-1fc004ab-0045-4a7e-a37a-12c7ebcd5ab0.png)


2 .Downloading all the files of a given private / Shared folder link:
Parameters: python auto_download.py **Folder Link** 
Eg. python auto_download.py --folder_link https://drive.google.com/drive/folders/1Lj9uZFpMNUz6xVa12UmY3jUCZ-lSGlud?usp=sharing
![Capture](https://user-images.githubusercontent.com/38622189/154617763-69107592-7c72-408d-901f-6e920ccc57a4.JPG)

![Untitled](https://user-images.githubusercontent.com/38622189/154618319-97ca1e85-4437-4cdd-ac34-e86a824685a4.png)

Note:
Libraries added: pydrive for authentication & connection to drive.
** Please generate client_secrets.json from Google cloud Platform, & keep it in the same directory as that of script, to make use of these new features.

**Comment by jitendar-singh** [comment]
- No test cases defined
- Donot see any  use of API , didnt understand the problem
- Bad coding sytle using drive ulr directly in the code.
